// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartWarehouse.PlatformCore.Infrastructure.Persistence;

#nullable disable

namespace SmartWarehouse.PlatformCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformCoreDbContext))]
    [Migration("20260409100409_ExpandWcsExecutionTaskRuntimeStateModel")]
    partial class ExpandWcsExecutionTaskRuntimeStateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.DeviceBindingRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceFamily")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HomeNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InitialNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShaftId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TopologyVersionId", "DeviceId");

                    b.ToTable("device_bindings", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.DeviceSessionRecord", b =>
                {
                    b.Property<string>("DeviceSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("DeviceSessionId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("LeaseUntil");

                    b.ToTable("device_sessions", "wcs");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.DeviceShadowRecord", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string[]>("ActiveCapabilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CarriedPayloadId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CarrierId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CarrierKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CurrentNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceFamily")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DispatchStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExecutionState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HealthState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MovementMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OccupiedShuttleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("SlotCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("StaticCapabilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("DeviceId");

                    b.HasIndex("CurrentNodeId");

                    b.HasIndex("DeviceFamily");

                    b.ToTable("device_shadows", "wcs");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.DigitalTwinDeviceProjectionRecord", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string[]>("ActiveCapabilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CurrentNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceFamily")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExecutionState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HealthState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeviceId");

                    b.HasIndex("CurrentNodeId");

                    b.ToTable("digital_twin_devices", "projection");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.DigitalTwinPayloadProjectionRecord", b =>
                {
                    b.Property<string>("PayloadId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CustodyHolderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CustodyHolderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Height")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Length")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("PayloadKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("Width")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("PayloadId");

                    b.HasIndex("CustodyHolderType", "CustodyHolderId");

                    b.ToTable("digital_twin_payloads", "projection");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.DigitalTwinReservationProjectionRecord", b =>
                {
                    b.Property<string>("ReservationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<string[]>("ReservedNodeIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ReservationId");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("digital_twin_reservations", "projection");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.DigitalTwinStationProjectionRecord", b =>
                {
                    b.Property<string>("StationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AttachedNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CurrentPayloadId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Readiness")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("StationId");

                    b.HasIndex("AttachedNodeId");

                    b.ToTable("digital_twin_stations", "projection");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.EndpointMappingRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EndpointId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EndpointKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServicePointId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TopologyVersionId", "EndpointId");

                    b.ToTable("endpoint_mappings", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.ExecutionTaskPlanRecord", b =>
                {
                    b.Property<string>("ExecutionTaskId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AssigneeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AssigneeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TaskRevision")
                        .HasColumnType("integer");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransferMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ExecutionTaskId");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "TaskRevision")
                        .IsUnique();

                    b.ToTable("execution_task_plans", "wes");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.ExecutionTaskRuntimeRecord", b =>
                {
                    b.Property<string>("ExecutionTaskId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActiveRuntimePhase")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AssigneeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AssigneeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParticipantRefs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("ReplanRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ResolutionHint")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetNodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TaskRevision")
                        .HasColumnType("integer");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransferMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ExecutionTaskId");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("JobId");

                    b.HasIndex("State", "AssigneeId");

                    b.ToTable("execution_task_runtime", "wcs");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.FaultRecord", b =>
                {
                    b.Property<string>("FaultId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FaultCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("FaultId");

                    b.HasIndex("SourceType", "SourceId", "State");

                    b.ToTable("faults", "wcs");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.InboxMessageRecord", b =>
                {
                    b.Property<string>("InboxId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("HandledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("InboxId");

                    b.HasIndex("HandledAt");

                    b.HasIndex("Source", "MessageId")
                        .IsUnique();

                    b.ToTable("inbox_messages", "integration");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.JobRecord", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Attributes")
                        .HasColumnType("text");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PayloadId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadRef")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReasonMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceEndpointId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetEndpointId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobId");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("PayloadId");

                    b.HasIndex("State", "Priority");

                    b.ToTable("jobs", "wes");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.JobRouteSegmentRecord", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("JobId", "SequenceNo");

                    b.HasIndex("JobId", "NodeId");

                    b.ToTable("job_route_segments", "wes");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.NorthboundIdempotencyRecord", b =>
                {
                    b.Property<string>("ClientOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ClientOrderId");

                    b.ToTable("northbound_idempotency", "integration");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.OutboxMessageRecord", b =>
                {
                    b.Property<string>("OutboxId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OutboxId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Producer", "MessageKind", "PublishedAt");

                    b.ToTable("outbox_messages", "integration");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.PayloadTransferJobProjectionRecord", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<string>("ClientOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LastExecutionTaskId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadRef")
                        .HasColumnType("jsonb");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReasonMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceEndpointId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetEndpointId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("JobId");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("State", "Priority");

                    b.ToTable("payload_transfer_jobs", "projection");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.PlatformEventJournalRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EventName", "OccurredAt");

                    b.ToTable("platform_event_journal", "audit");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.ReservationRecord", b =>
                {
                    b.Property<string>("ReservationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<string[]>("ReservedNodeIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ReservationId");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("reservations", "wcs");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.ResourceAssignmentRecord", b =>
                {
                    b.Property<string>("ExecutionTaskId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<string>("AssignmentRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ExecutionTaskId", "SequenceNo");

                    b.HasIndex("ExecutionTaskId", "AssignmentRole");

                    b.ToTable("resource_assignments", "wes");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.StationBoundaryStateRecord", b =>
                {
                    b.Property<string>("StationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AttachedNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("BufferCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("ControlMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CurrentPayloadId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Readiness")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("StationId");

                    b.HasIndex("AttachedNodeId")
                        .IsUnique();

                    b.HasIndex("Readiness");

                    b.ToTable("station_boundary_state", "wcs");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.TopologyEdgeRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EdgeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FromNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraversalMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("TopologyVersionId", "EdgeId");

                    b.HasIndex("TopologyVersionId", "FromNodeId");

                    b.HasIndex("TopologyVersionId", "ToNodeId");

                    b.ToTable("topology_edges", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.TopologyLevelRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LevelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("TopologyVersionId", "LevelId");

                    b.HasIndex("TopologyVersionId", "Ordinal")
                        .IsUnique();

                    b.ToTable("topology_levels", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.TopologyNodeRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LevelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServicePointId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShaftId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("TopologyVersionId", "NodeId");

                    b.HasIndex("TopologyVersionId", "LevelId");

                    b.HasIndex("TopologyVersionId", "NodeType");

                    b.ToTable("topology_nodes", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.TopologyServicePointRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ServicePointId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PassiveSemantics")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServicePointType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TopologyVersionId", "ServicePointId");

                    b.HasIndex("TopologyVersionId", "NodeId")
                        .IsUnique();

                    b.ToTable("topology_service_points", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.TopologyShaftRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShaftId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CarrierDeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.HasKey("TopologyVersionId", "ShaftId");

                    b.HasIndex("TopologyVersionId", "CarrierDeviceId")
                        .IsUnique();

                    b.ToTable("topology_shafts", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.TopologyShaftStopRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShaftId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LevelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CarrierNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TransferPointId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("TopologyVersionId", "ShaftId", "LevelId");

                    b.HasIndex("TopologyVersionId", "CarrierNodeId")
                        .IsUnique();

                    b.HasIndex("TopologyVersionId", "TransferPointId")
                        .IsUnique();

                    b.ToTable("topology_shaft_stops", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.TopologyStationRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AttachedNodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("BufferCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("ControlMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("TopologyVersionId", "StationId");

                    b.HasIndex("TopologyVersionId", "AttachedNodeId");

                    b.ToTable("topology_stations", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.TopologyVersionRecord", b =>
                {
                    b.Property<string>("TopologyVersionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TopologyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("TopologyVersionId");

                    b.HasIndex("TopologyId", "Version")
                        .IsUnique();

                    b.ToTable("topology_versions", "config");
                });

            modelBuilder.Entity("SmartWarehouse.PlatformCore.Infrastructure.Persistence.Model.WebhookDeliveryRecord", b =>
                {
                    b.Property<string>("WebhookDeliveryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("WebhookDeliveryId");

                    b.HasIndex("DeliveryState", "NextAttemptAt");

                    b.HasIndex("EventId", "TargetUrl");

                    b.ToTable("webhook_deliveries", "integration");
                });
#pragma warning restore 612, 618
        }
    }
}
